<?php
require_once 'includes/config.php';
requireAuth();
$user = auth();

$ps = db()->prepare("SELECT * FROM profiles WHERE user_id=?");
$ps->execute([$user['id']]);
$profile = $ps->fetch();

if (!$profile) {
    flash('error','Please complete your profile first to generate a CV.');
    header('Location:'.BASE_URL.'/profile.php'); exit;
}

$skills = json_decode($profile['skills']          ?? '[]', true) ?: [];
$exp    = json_decode($profile['experience']      ?? '[]', true) ?: [];
$edu    = json_decode($profile['education']       ?? '[]', true) ?: [];
$langs  = json_decode($profile['languages']       ?? '[]', true) ?: [];
$certs  = json_decode($profile['certifications']  ?? '[]', true) ?: [];

$lang = ($_GET['lang'] ?? 'en') === 'ko' ? 'ko' : 'en';
$isKo = $lang === 'ko';

// ── Auto-translate content for Korean version ──────────────
// Uses session cache so translation only happens once per session
function translateToKorean(string $text): string {
    if (empty(trim($text))) return $text;
    // If already Korean characters, skip
    if (preg_match('/[\x{AC00}-\x{D7AF}\x{1100}-\x{11FF}]/u', $text)) return $text;
    $cacheKey = 'cv_tr_'.md5($text);
    if (isset($_SESSION[$cacheKey])) return $_SESSION[$cacheKey];
    try {
        $ch = curl_init('https://api.anthropic.com/v1/messages');
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST           => true,
            CURLOPT_HTTPHEADER     => [
                'Content-Type: application/json',
                'x-api-key: '.(defined('ANTHROPIC_API_KEY') ? ANTHROPIC_API_KEY : ''),
                'anthropic-version: 2023-06-01',
            ],
            CURLOPT_POSTFIELDS => json_encode([
                'model'      => 'claude-haiku-4-5-20251001',
                'max_tokens' => 500,
                'messages'   => [[
                    'role'    => 'user',
                    'content' => 'Translate the following text to Korean for a professional CV/이력서. Return ONLY the translated text, nothing else. Keep proper nouns, company names, and technical terms in their original form if commonly used as-is in Korean CVs. Text: '.$text
                ]]
            ]),
            CURLOPT_TIMEOUT => 8,
        ]);
        $res  = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($code === 200) {
            $data = json_decode($res, true);
            $tr   = trim($data['content'][0]['text'] ?? '');
            if ($tr) { $_SESSION[$cacheKey] = $tr; return $tr; }
        }
    } catch (Exception $e) {}
    return $text; // fallback: return original
}

// Translate helper — only translates when Korean mode active
function tr(string $text): string {
    global $isKo;
    return $isKo ? translateToKorean($text) : $text;
}

// ── Labels ────────────────────────────────────────────────
$L = $isKo ? [
    'summary'    => '자기소개',
    'experience' => '경력사항',
    'education'  => '학력사항',
    'skills'     => '보유 기술',
    'languages'  => '어학 능력',
    'certs'      => '자격증 및 수료',
    'academic'   => '학업 정보',
    'links'      => '링크',
    'university' => '대학교',
    'department' => '학과',
    'graduation' => '졸업 예정',
    'generated'  => '생성',
    'print'      => '⬇ PDF 다운로드 / 인쇄',
    'edit'       => '✏️ 프로필 편집',
    'back'       => '← 프로필로 돌아가기',
    'personal'   => '인적사항',
    'name'       => '성명',
    'email'      => '이메일',
    'phone'      => '연락처',
    'location'   => '거주지',
    'school'     => '학교',
    'dept'       => '학과',
    'portfolio'  => '포트폴리오',
    'date'       => date('Y년 m월 d일'),
] : [
    'summary'    => 'Professional Summary',
    'experience' => 'Work Experience',
    'education'  => 'Education',
    'skills'     => 'Skills',
    'languages'  => 'Languages',
    'certs'      => 'Certifications',
    'academic'   => 'Academic Info',
    'links'      => 'Links',
    'university' => 'University',
    'department' => 'Department',
    'graduation' => 'Graduation',
    'generated'  => 'Generated by',
    'print'      => '⬇ Download / Print PDF',
    'edit'       => '✏️ Edit Profile',
    'back'       => '← Back to Profile',
    'personal'   => 'Personal Info',
    'name'       => 'Name',
    'email'      => 'Email',
    'phone'      => 'Phone',
    'location'   => 'Location',
    'school'     => 'University',
    'dept'       => 'Department',
    'portfolio'  => 'Portfolio',
    'date'       => date('F j, Y'),
];
?>
<!DOCTYPE html>
<html lang="<?= $isKo?'ko':'en' ?>">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title><?= clean($user['name']) ?> — <?= $isKo?'이력서':'CV' ?> | Campus Connect X</title>
<?php if($isKo): ?>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&family=Noto+Serif+KR:wght@400;700&display=swap" rel="stylesheet">
<?php else: ?>
<link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,400&display=swap" rel="stylesheet">
<?php endif; ?>
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500;600&display=swap');
*,*::before,*::after { box-sizing:border-box; margin:0; padding:0; }
body {
  font-family: <?= $isKo?"'Noto Sans KR',sans-serif":"'DM Sans',sans-serif" ?>;
  background: #F0F4FF;
  color: #0F172A;
  -webkit-font-smoothing: antialiased;
  <?= $isKo ? 'word-break:keep-all;' : '' ?>
}
a { color:#2563EB; text-decoration:none; }

/* ── ACTION BAR ─────────────────────────────── */
.cv-actions {
  max-width: 920px; margin: 0 auto;
  padding: 18px 24px;
  display: flex; align-items: center; justify-content: space-between;
  gap: 10px; flex-wrap: wrap;
}
.btn {
  display: inline-flex; align-items: center; gap: 7px;
  padding: 9px 18px; border-radius: 10px;
  font-size: 13px; font-weight: 600;
  border: none; cursor: pointer;
  font-family: inherit; text-decoration: none; transition: all .2s;
}
.btn-primary { background:#2563EB; color:#fff; }
.btn-primary:hover { background:#1D4ED8; }
.btn-ghost { background:#F1F5F9; color:#475569; border:1px solid #E2E8F0; }
.btn-ghost:hover { background:#E2E8F0; }
.btn-success { background:#10B981; color:#fff; }
.btn-success:hover { background:#059669; }

/* Language tabs */
.lang-tabs { display:flex; gap:5px; background:#E2E8F0; border-radius:10px; padding:4px; }
.lang-tab {
  padding: 6px 14px; border-radius: 7px;
  font-size: 12px; font-weight: 600;
  text-decoration: none; color: #64748B; transition: .15s;
}
.lang-tab.active { background:#fff; color:#0F172A; box-shadow:0 1px 4px rgba(0,0,0,.1); }

/* Translate notice */
.tr-notice {
  max-width: 920px; margin: 0 auto 0;
  padding: 0 24px 10px;
}
.tr-badge {
  display: inline-flex; align-items: center; gap: 6px;
  background: #ECFDF5; border: 1px solid #6EE7B7;
  color: #065F46; font-size: 11px; font-weight: 600;
  padding: 5px 12px; border-radius: 20px;
}

/* ── CV WRAPPER ─────────────────────────────── */
.cv-wrap { max-width: 920px; margin: 0 auto; padding: 0 24px 48px; }
.cv-paper {
  background: #fff; border-radius: 16px;
  overflow: hidden; box-shadow: 0 10px 40px rgba(0,0,0,.12);
}

/* ── HEADER: English ─────────────────────────── */
<?php if(!$isKo): ?>
.cv-head {
  background: linear-gradient(130deg,#0F172A 0%,#1E3A5F 55%,#2D1B69 100%);
  padding: 40px 48px; color: #fff;
  display: flex; justify-content: space-between;
  align-items: flex-start; gap: 24px;
  position: relative; overflow: hidden;
}
.cv-head::after {
  content: ''; position: absolute; top: -60px; right: -60px;
  width: 280px; height: 280px;
  background: radial-gradient(circle,rgba(139,92,246,.15) 0%,transparent 70%);
  border-radius: 50%;
}
.cv-name { font-family:'Syne',sans-serif; font-size:34px; font-weight:800; margin-bottom:4px; line-height:1.1; }
.cv-role { font-size:15px; color:rgba(255,255,255,.6); margin-bottom:16px; }
.cv-av {
  width:84px; height:84px; border-radius:50%;
  background:linear-gradient(135deg,#2563EB,#8B5CF6);
  display:flex; align-items:center; justify-content:center;
  font-family:'Syne',sans-serif; font-size:30px; font-weight:800; color:#fff;
  flex-shrink:0; border:3px solid rgba(255,255,255,.2); z-index:1; overflow:hidden;
}

/* ── HEADER: Korean ──────────────────────────── */
<?php else: ?>
.cv-head {
  background: linear-gradient(135deg,#003478 0%,#CD2E3A 100%);
  padding: 36px 48px; color: #fff;
  display: flex; justify-content: space-between;
  align-items: flex-start; gap: 24px;
  position: relative; overflow: hidden;
}
.cv-head::before {
  content: '대한민국';
  position: absolute; top: -10px; right: 48px;
  font-family: 'Noto Serif KR',serif; font-size: 64px; font-weight: 700;
  color: rgba(255,255,255,.05); letter-spacing: -.02em;
  line-height: 1; white-space: nowrap;
}
.cv-name {
  font-family: 'Noto Serif KR',serif;
  font-size: 30px; font-weight: 700;
  margin-bottom: 4px; line-height: 1.2; letter-spacing: -.02em;
}
.cv-role { font-size: 14px; color: rgba(255,255,255,.65); margin-bottom: 14px; }
.cv-av {
  width: 88px; height: 110px;
  border-radius: 4px; /* Korean CV: rectangular photo */
  background: linear-gradient(135deg,#003478,#CD2E3A);
  display: flex; align-items: center; justify-content: center;
  font-family: 'Noto Serif KR',serif; font-size: 26px; font-weight: 700; color: #fff;
  flex-shrink: 0; border: 2px solid rgba(255,255,255,.25); z-index: 1; overflow: hidden;
}
<?php endif; ?>

.cv-contacts { display:flex; flex-wrap:wrap; gap:8px 16px; }
.cv-contact { font-size:12px; color:rgba(255,255,255,.65); display:flex; align-items:center; gap:5px; }

/* ── BODY GRID ──────────────────────────────── */
.cv-body { display:grid; grid-template-columns:1fr <?= $isKo?'240px':'270px' ?>; }
.cv-main { padding:36px 40px; border-right:1px solid #E2E8F0; }
.cv-side { padding:30px 24px; background:<?= $isKo?'#F5F7FA':'#F8FAFF' ?>; }

/* ── SECTION TITLES ─────────────────────────── */
.cv-sec { margin-bottom:28px; }
.cv-sec:last-child { margin-bottom:0; }
.cv-sec-title {
  font-family: <?= $isKo?"'Noto Sans KR',sans-serif":"'Syne',sans-serif" ?>;
  font-size: <?= $isKo?'12px':'11px' ?>;
  font-weight: 700;
  text-transform: <?= $isKo?'none':'uppercase' ?>;
  letter-spacing: <?= $isKo?'0':'.12em' ?>;
  color: <?= $isKo?'#003478':'#2563EB' ?>;
  margin-bottom: 14px; padding-bottom: 7px;
  border-bottom: 2px solid <?= $isKo?'#003478':'#EFF6FF' ?>;
}
.cv-summary { font-size:<?= $isKo?'13.5px':'14px' ?>; color:#475569; line-height:<?= $isKo?'1.9':'1.75' ?>; }

/* ── TIMELINE ───────────────────────────────── */
.cv-item {
  margin-bottom: 18px; padding-left: 14px;
  border-left: 2px solid <?= $isKo?'#003478':'#2563EB' ?>;
}
.cv-item:last-child { margin-bottom:0; }
.cv-item-hdr { display:flex; justify-content:space-between; align-items:flex-start; gap:8px; margin-bottom:2px; }
.cv-item-title { font-size:14px; font-weight:600; color:#0F172A; }
.cv-item-period { font-size:11px; color:#94A3B8; white-space:nowrap; flex-shrink:0; }
.cv-item-org { font-size:12px; color:<?= $isKo?'#003478':'#2563EB' ?>; font-weight:500; margin-bottom:4px; }
.cv-item-desc { font-size:12px; color:#64748B; line-height:1.65; }

/* ── SIDE COLUMN ────────────────────────────── */
.cv-side-sec { margin-bottom:22px; }
.cv-side-sec:last-child { margin-bottom:0; }
.cv-side-title {
  font-family: <?= $isKo?"'Noto Sans KR',sans-serif":"'Syne',sans-serif" ?>;
  font-size: <?= $isKo?'12px':'11px' ?>;
  font-weight: 700;
  text-transform: <?= $isKo?'none':'uppercase' ?>;
  letter-spacing: <?= $isKo?'0':'.1em' ?>;
  color: <?= $isKo?'#CD2E3A':'#8B5CF6' ?>;
  margin-bottom: 10px; padding-bottom: 5px;
  border-bottom: 2px solid <?= $isKo?'rgba(205,46,58,.15)':'#F5F3FF' ?>;
}
.skill-pill {
  display: inline-block;
  background: <?= $isKo?'#EEF2FF':'#EFF6FF' ?>;
  color: <?= $isKo?'#003478':'#1D4ED8' ?>;
  font-size: 11px; font-weight: 600;
  padding: 4px 10px; border-radius: 99px; margin: 3px;
}
.cv-lang { display:flex; align-items:center; gap:8px; margin-bottom:6px; font-size:13px; color:#475569; }
.cv-cert { font-size:12px; color:#475569; padding:5px 0; border-bottom:1px solid #F1F5F9; }
.cv-link { font-size:12px; margin-bottom:6px; display:block; }
.cv-meta-row { margin-bottom:10px; }
.cv-meta-lbl { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.08em; color:#94A3B8; margin-bottom:2px; }
.cv-meta-val { font-size:13px; color:#475569; }

/* ── Korean personal info table ─────────────── */
<?php if($isKo): ?>
.ko-personal {
  background:#FAFBFD; border:1px solid #E2E8F0;
  border-radius:8px; padding:14px 16px; margin-bottom:20px;
}
.ko-personal-row { display:flex; margin-bottom:6px; font-size:12.5px; }
.ko-personal-row:last-child { margin-bottom:0; }
.ko-personal-lbl { width:72px; flex-shrink:0; font-weight:700; color:#475569; font-size:11.5px; }
.ko-personal-val { color:#0F172A; }
<?php endif; ?>

/* ── STAMP ───────────────────────────────────── */
.cv-stamp { font-size:10px; color:#94A3B8; text-align:center; padding-top:14px; border-top:1px solid #E2E8F0; }

/* ── PRINT ───────────────────────────────────── */
@media print {
  body { background:#fff; }
  .cv-actions, .tr-notice { display:none !important; }
  .cv-wrap { padding:0; max-width:100%; }
  .cv-paper { border-radius:0; box-shadow:none; }
  .cv-body { grid-template-columns:1fr <?= $isKo?'220px':'240px' ?>; }
  .cv-head { padding:28px 36px; }
  .cv-main { padding:26px 32px; }
  .cv-side { padding:26px 20px; }
}
@media(max-width:700px) {
  .cv-body { grid-template-columns:1fr; }
  .cv-side { border-top:1px solid #E2E8F0; }
  .cv-head { flex-direction:column; }
  .cv-main, .cv-head { padding:22px; }
  .cv-side { padding:22px; }
  .cv-name { font-size:26px; }
  .cv-actions { padding:14px; }
  .lang-tabs { flex-wrap:wrap; }
}
</style>
</head>
<body>

<!-- ══ ACTION BAR ════════════════════════════════════════ -->
<div class="cv-actions">
  <a href="<?= BASE_URL ?>/profile.php" class="btn btn-ghost"><?= $L['back'] ?></a>
  <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">
    <div class="lang-tabs">
      <a href="?lang=en" class="lang-tab <?= !$isKo?'active':'' ?>">🇬🇧 English</a>
      <a href="?lang=ko" class="lang-tab <?= $isKo?'active':'' ?>">🇰🇷 한국어</a>
    </div>
    <a href="<?= BASE_URL ?>/profile.php" class="btn btn-ghost"><?= $L['edit'] ?></a>
    <button onclick="window.print()" class="btn btn-success"><?= $L['print'] ?></button>
  </div>
</div>

<?php if($isKo): ?>
<div class="tr-notice">
  <span class="tr-badge">✨ AI 자동 번역 — 프로필 내용이 한국어로 자동 번역됩니다</span>
</div>
<?php endif; ?>

<!-- ══ CV PAPER ══════════════════════════════════════════ -->
<div class="cv-wrap">
<div class="cv-paper">

  <!-- HEADER -->
  <div class="cv-head">
    <div style="flex:1;min-width:0;">
      <div class="cv-name"><?= clean($user['name']) ?></div>
      <div class="cv-role">
        <?= clean($user['department'] ?? ($isKo?'학생':'Student')) ?>
        <?= $user['university'] ? ' · '.clean($user['university']) : '' ?>
      </div>
      <div class="cv-contacts">
        <span class="cv-contact">✉ <?= clean($user['email']) ?></span>
        <?php if(!empty($profile['phone'])): ?><span class="cv-contact"><?= $isKo?'☎':'📞' ?> <?= clean($profile['phone']) ?></span><?php endif; ?>
        <?php if(!empty($profile['city'])): ?><span class="cv-contact">📍 <?= clean($profile['city']) ?><?= !empty($profile['country'])?', '.clean($profile['country']):'' ?></span><?php endif; ?>
        <?php if(!empty($profile['linkedin'])): ?><span class="cv-contact">🔗 <a href="<?= clean($profile['linkedin']) ?>" style="color:rgba(255,255,255,.65);">LinkedIn</a></span><?php endif; ?>
        <?php if(!empty($profile['github'])): ?><span class="cv-contact">💻 <a href="<?= clean($profile['github']) ?>" style="color:rgba(255,255,255,.65);">GitHub</a></span><?php endif; ?>
        <?php if(!empty($profile['website'])): ?><span class="cv-contact">🌐 <a href="<?= clean($profile['website']) ?>" style="color:rgba(255,255,255,.65);"><?= $isKo?'포트폴리오':'Portfolio' ?></a></span><?php endif; ?>
      </div>
    </div>

    <!-- Avatar: circle (EN) vs portrait rectangle (KO) -->
    <div class="cv-av">
      <?php if(!empty($user['avatar']) && file_exists(__DIR__.'/'.$user['avatar'])): ?>
        <img src="<?= BASE_URL.'/'.$user['avatar'] ?>"
             alt="Profile Photo"
             style="width:100%;height:100%;object-fit:cover;<?= $isKo?'border-radius:4px;':'border-radius:50%;' ?>">
      <?php else: ?>
        <?= initials($user['name']) ?>
      <?php endif; ?>
    </div>
  </div>

  <!-- BODY -->
  <div class="cv-body">

    <!-- ═══ MAIN COLUMN ══════════════════════════════════ -->
    <div class="cv-main">

      <?php if($isKo): ?>
      <!-- Korean: 인적사항 table at top -->
      <div class="cv-sec">
        <div class="cv-sec-title"><?= $L['personal'] ?></div>
        <div class="ko-personal">
          <div class="ko-personal-row"><span class="ko-personal-lbl"><?=$L['name']?></span><span class="ko-personal-val"><?= clean($user['name']) ?></span></div>
          <div class="ko-personal-row"><span class="ko-personal-lbl"><?=$L['email']?></span><span class="ko-personal-val"><?= clean($user['email']) ?></span></div>
          <?php if(!empty($profile['phone'])): ?><div class="ko-personal-row"><span class="ko-personal-lbl"><?=$L['phone']?></span><span class="ko-personal-val"><?= clean($profile['phone']) ?></span></div><?php endif; ?>
          <?php if(!empty($profile['city'])): ?><div class="ko-personal-row"><span class="ko-personal-lbl"><?=$L['location']?></span><span class="ko-personal-val"><?= clean($profile['city']) ?><?= !empty($profile['country'])?', '.clean($profile['country']):'' ?></span></div><?php endif; ?>
          <?php if($user['university']): ?><div class="ko-personal-row"><span class="ko-personal-lbl"><?=$L['school']?></span><span class="ko-personal-val"><?= clean($user['university']) ?></span></div><?php endif; ?>
          <?php if($user['department']): ?><div class="ko-personal-row"><span class="ko-personal-lbl"><?=$L['dept']?></span><span class="ko-personal-val"><?= clean($user['department']) ?></span></div><?php endif; ?>
        </div>
      </div>
      <?php endif; ?>

      <!-- Summary / 자기소개 — auto-translated for KO -->
      <?php if(!empty($profile['summary'])): ?>
      <div class="cv-sec">
        <div class="cv-sec-title"><?= $L['summary'] ?></div>
        <p class="cv-summary"><?= nl2br(clean(tr($profile['summary']))) ?></p>
      </div>
      <?php endif; ?>

      <!-- Experience / 경력사항 — titles & descriptions translated -->
      <?php if(!empty($exp)): ?>
      <div class="cv-sec">
        <div class="cv-sec-title"><?= $L['experience'] ?></div>
        <?php foreach($exp as $e): ?>
        <div class="cv-item">
          <div class="cv-item-hdr">
            <div class="cv-item-title"><?= clean(tr($e['title'])) ?></div>
            <span class="cv-item-period"><?= clean($e['period']) ?></span>
          </div>
          <div class="cv-item-org"><?= clean($e['org']) /* company names stay as-is */ ?></div>
          <?php if(!empty($e['desc'])): ?><div class="cv-item-desc"><?= nl2br(clean(tr($e['desc']))) ?></div><?php endif; ?>
        </div>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>

      <!-- Education / 학력사항 — degrees translated -->
      <?php if(!empty($edu)): ?>
      <div class="cv-sec">
        <div class="cv-sec-title"><?= $L['education'] ?></div>
        <?php foreach($edu as $e): ?>
        <div class="cv-item" style="border-left-color:<?= $isKo?'#CD2E3A':'#8B5CF6' ?>;">
          <div class="cv-item-hdr">
            <div class="cv-item-title"><?= clean(tr($e['title'])) ?></div>
            <span class="cv-item-period"><?= clean($e['period']) ?></span>
          </div>
          <div class="cv-item-org" style="color:<?= $isKo?'#CD2E3A':'#8B5CF6' ?>;"><?= clean($e['org']) ?></div>
          <?php if(!empty($e['desc'])): ?><div class="cv-item-desc"><?= nl2br(clean(tr($e['desc']))) ?></div><?php endif; ?>
        </div>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>

      <!-- Korean: Certifications in main column (KO convention) -->
      <?php if($isKo && !empty($certs)): ?>
      <div class="cv-sec">
        <div class="cv-sec-title"><?= $L['certs'] ?></div>
        <?php foreach($certs as $c): ?>
        <div class="cv-item" style="border-left-color:#CD2E3A;">
          <div class="cv-item-title" style="font-size:13px;">🏆 <?= clean(tr($c)) ?></div>
        </div>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>

    </div><!-- /cv-main -->

    <!-- ═══ SIDE COLUMN ══════════════════════════════════ -->
    <div class="cv-side">

      <!-- Skills -->
      <?php if(!empty($skills)): ?>
      <div class="cv-side-sec">
        <div class="cv-side-title"><?= $L['skills'] ?></div>
        <?php foreach($skills as $sk): ?>
        <span class="skill-pill"><?= clean($sk) /* tech skills stay as-is */ ?></span>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>

      <!-- Languages -->
      <?php if(!empty($langs)): ?>
      <div class="cv-side-sec">
        <div class="cv-side-title"><?= $L['languages'] ?></div>
        <?php foreach($langs as $l): ?>
        <div class="cv-lang">🗣 <?= clean($l) ?></div>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>

      <!-- Certifications (English side column) -->
      <?php if(!$isKo && !empty($certs)): ?>
      <div class="cv-side-sec">
        <div class="cv-side-title"><?= $L['certs'] ?></div>
        <?php foreach($certs as $c): ?><div class="cv-cert">🏆 <?= clean($c) ?></div><?php endforeach; ?>
      </div>
      <?php endif; ?>

      <!-- Academic Info -->
      <div class="cv-side-sec">
        <div class="cv-side-title"><?= $L['academic'] ?></div>
        <?php if($user['university']): ?><div class="cv-meta-row"><div class="cv-meta-lbl"><?=$L['university']?></div><div class="cv-meta-val"><?= clean($user['university']) ?></div></div><?php endif; ?>
        <?php if($user['department']): ?><div class="cv-meta-row"><div class="cv-meta-lbl"><?=$L['department']?></div><div class="cv-meta-val"><?= clean($user['department']) ?></div></div><?php endif; ?>
        <?php if(!empty($user['graduation_year'])): ?><div class="cv-meta-row"><div class="cv-meta-lbl"><?=$L['graduation']?></div><div class="cv-meta-val"><?= clean($user['graduation_year']) ?></div></div><?php endif; ?>
      </div>

      <!-- Links -->
      <?php if(!empty($profile['linkedin'])||!empty($profile['github'])||!empty($profile['website'])): ?>
      <div class="cv-side-sec">
        <div class="cv-side-title"><?= $L['links'] ?></div>
        <?php if(!empty($profile['linkedin'])): ?><a class="cv-link" href="<?= clean($profile['linkedin']) ?>">🔗 LinkedIn</a><?php endif; ?>
        <?php if(!empty($profile['github'])): ?><a class="cv-link" href="<?= clean($profile['github']) ?>">💻 GitHub</a><?php endif; ?>
        <?php if(!empty($profile['website'])): ?><a class="cv-link" href="<?= clean($profile['website']) ?>">🌐 <?= $isKo?'포트폴리오':'Portfolio' ?></a><?php endif; ?>
      </div>
      <?php endif; ?>

      <!-- Stamp -->
      <div class="cv-side-sec cv-stamp">
        <?= $L['generated'] ?><br>
        <strong style="color:<?= $isKo?'#003478':'#2563EB' ?>;">Campus Connect X</strong>
        <br><span style="font-size:9px;color:#CBD5E1;"><?= $L['date'] ?></span>
      </div>

    </div><!-- /cv-side -->
  </div><!-- /cv-body -->
</div><!-- /cv-paper -->
</div><!-- /cv-wrap -->

</body>
</html>